@startuml
left to right direction
actor "User" as AC_U
actor "Registered user" as AC_FT
actor "Business" as AC_B

rectangle "Searching and Filtering Services" {
    usecase "Search Services on a map" as UC_SM
    usecase "Recommendations" as UC_RS
    usecase "Filter Services" AS UC_FS
    usecase "Service order history" as UC_SO
}
rectangle "Booking Services" {
    usecase "Book service" as UC_BS
    usecase "Refund request option" as UC_RR
    usecase "Payment info" as UC_PI
}

rectangle "Provide Services" {
    usecase "Providing time slots" as UC_PS
    usecase "Service customization" as UC_SC
    usecase "View and respond to Client reviews" as UC_RC
}

UC_BS .u.> UC_SM : <<extend>>
UC_BS .u.> UC_RS : <<extend>>
UC_BS .u.> UC_PI : <<extend>>
UC_BS .u.> UC_PS : <<extend>>
UC_SM .l.> UC_FS : <<include>>
UC_RS .r.> UC_FS : <<include>>
UC_RR .r.> UC_PI : <<include>>

UC_PS .u.> UC_SC : <<extend>>

AC_U --> UC_SM
AC_U --> UC_PI
AC_U --> UC_RR
AC_FT -u-|> AC_U
AC_FT --> UC_RS
AC_FT --> UC_SO

AC_B --> UC_PS
AC_B --> UC_SC
AC_B --> UC_RC
@enduml