@startuml
left to right direction
actor "User" as AC_U
actor "Registered user" as AC_FT
actor "Business" as AC_B

rectangle "Searching and Filtering Services" {
    usecase "Search for Services on a map" as UC_SM
    usecase "Filtering Services" AS UC_FS
    usecase "Service order history" as UC_SO
}
rectangle "Booking Services" {
    usecase "Book service" as UC_BS
    usecase "Refund request option" as UC_RR
}

rectangle "Provide Services" {
    usecase "Providing time slots" as UC_PS
    usecase "Service customization" as UC_SC
    usecase "View and respond to Client reviews" as UC_RC
    usecase "Add new Certifications" as UC_MC
    usecase "Control Performance stats" as UC_CPS
}


UC_SM .l.> UC_FS : <<include>>

UC_PS .u.> UC_SC : <<extend>>

AC_U --> UC_SM
AC_U --> UC_RR
AC_U --> UC_BS
AC_U --> UC_FS
AC_FT -u-|> AC_U
AC_FT --> UC_SO

AC_B --> UC_PS
AC_B --> UC_SC
AC_B --> UC_RC
AC_B --> UC_MC
AC_B --> UC_CPS
@enduml