@startuml
hide empty description
state "Displaying Details\n of the service" as DetailsService
state "Displaying \n Slots not found PopUp" as SlotsNotFound
state "Displaying Calendar\nwith available time slots" as Calendar
state "Showing continue button" as ContinueButton
state "Displaying Slot is\n not available PopUp" as SlotNotAvailable
state "Displaying order details" as OrderDetails
state "Selecting Payment methods" as PaymentMethods
state "Confirming booking" as BookingConfirmed

[*] -r-> DetailsService
DetailsService -d-> SlotsNotFound : No slots found
DetailsService -r-> Calendar : Slots found
Calendar -r-> ContinueButton : Selected available slot
Calendar -d-> SlotNotAvailable : Selected \n unavailable slot
ContinueButton -r-> OrderDetails : User clicks continue
OrderDetails -d-> PaymentMethods : User confirms \n details of the service
PaymentMethods -d-> BookingConfirmed : Payment completed

BookingConfirmed -d-> [*]: Bookin is confirmed
SlotsNotFound -d-> [*] : Can't book the service
SlotNotAvailable -d-> Calendar : Force to select \n available slot
OrderDetails -d-> [*] : Details of the service \n are not confirmed
@enduml